NAME: shop-reviews
LAST DEPLOYED: Fri Feb 23 14:52:59 2024
NAMESPACE: chris2
STATUS: pending-install
REVISION: 1
TEST SUITE: None
HOOKS:
MANIFEST:
---
# Source: shop-reviews/templates/pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget 
metadata:
  name: espresso-shop-reviews-v1
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app:
      version: v1
      version: v2
      app.kubernetes.io/name: shop-reviews
      app.kubernetes.io/instance: shop-reviews
---
# Source: shop-reviews/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shop-reviews
  labels:
    app: shop-reviews
    helm.sh/chart: shop-reviews-0.1.0
    version: v1
    version: v2
    app.kubernetes.io/name: shop-reviews
    app.kubernetes.io/instance: shop-reviews
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: shop-reviews/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-reviews
  labels:
    app: shop-reviews
    helm.sh/chart: shop-reviews-0.1.0
    version: v1
    version: v2
    app.kubernetes.io/name: shop-reviews
    app.kubernetes.io/instance: shop-reviews
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      version: v1
      version: v2
      app.kubernetes.io/name: shop-reviews
      app.kubernetes.io/instance: shop-reviews
  template:
    metadata:
      labels:
        app: shop-reviews
        helm.sh/chart: shop-reviews-0.1.0
        version: v1
        version: v2
        app.kubernetes.io/name: shop-reviews
        app.kubernetes.io/instance: shop-reviews
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: shop-reviews
      securityContext:
        {}
      containers:
        - name: shop-reviews
          securityContext:
            {}
          image: "chrisdylan/expresso:reviews"
          imagePullPolicy: Always
          env:
          - name: SERVICE_VERSION
            value: v1
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
# Source: shop-reviews/templates/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shop-reviews
  labels:
    app: shop-reviews
    helm.sh/chart: shop-reviews-0.1.0
    version: v1
    version: v2
    app.kubernetes.io/name: shop-reviews
    app.kubernetes.io/instance: shop-reviews
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shop-reviews
  minReplicas: 1
  maxReplicas: 100
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80

NOTES:
1. Get the application URL by running these commands:
  export NODE_PORT=$(kubectl get --namespace chris2 -o jsonpath="{.spec.ports[0].nodePort}" services shop-reviews)
  export NODE_IP=$(kubectl get nodes --namespace chris2 -o jsonpath="{.items[0].status.addresses[0].address}")
  echo http://$NODE_IP:$NODE_PORT
