apiVersion: policy/v1
kind: PodDisruptionBudget 
metadata:
  name: espresso-shop-reviews-v1
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: {{- include "shop-reviews.selectorLabels" . | nindent 6 }}
