apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "espresso-shop-product-catalog.fullname" . }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: {{- include "espresso-shop-product-catalog.selectorLabels" . | nindent 6 }}
