apiVersion: v1
kind: Secret
metadata:
  name: regcred
data:
  .dockerconfigjson: "ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIlkyaHlhWE5rZVd4aGJqcEVlV3hoYmpJek4wQT0iCgkJfQoJfQp9"
type: kubernetes.io/dockerconfigjson
