NAME: espresso-shop-reviews-v2
LAST DEPLOYED: Fri Feb 23 12:59:40 2024
NAMESPACE: chris2
STATUS: pending-install
REVISION: 1
TEST SUITE: None
HOOKS:
MANIFEST:
---
# Source: espresso-shop-reviews-v2/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: espresso-shop-reviews-v2
  labels:
    app: espresso-shop-reviews-v2
    helm.sh/chart: espresso-shop-reviews-v2-0.1.0
    version: v2
    app.kubernetes.io/name: espresso-shop-reviews-v2
    app.kubernetes.io/instance: espresso-shop-reviews-v2
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: espresso-shop-reviews-v2/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: espresso-shop-reviews-svc
  labels:
    app: espresso-shop-reviews-v2
    helm.sh/chart: espresso-shop-reviews-v2-0.1.0
    version: v2
    app.kubernetes.io/name: espresso-shop-reviews-v2
    app.kubernetes.io/instance: espresso-shop-reviews-v2
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: NodePort
  ports:
    - port: 8092
      targetPort: http
      protocol: TCP
      name: http
  selector:
    version: v2
    app.kubernetes.io/name: espresso-shop-reviews-v2
    app.kubernetes.io/instance: espresso-shop-reviews-v2
---
# Source: espresso-shop-reviews-v2/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: espresso-shop-reviews-v2
  labels:
    app: espresso-shop-reviews-v2
    helm.sh/chart: espresso-shop-reviews-v2-0.1.0
    version: v2
    app.kubernetes.io/name: espresso-shop-reviews-v2
    app.kubernetes.io/instance: espresso-shop-reviews-v2
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      version: v2
      app.kubernetes.io/name: espresso-shop-reviews-v2
      app.kubernetes.io/instance: espresso-shop-reviews-v2
  template:
    metadata:
      labels:
        app: espresso-shop-reviews-v2
        helm.sh/chart: espresso-shop-reviews-v2-0.1.0
        version: v2
        app.kubernetes.io/name: espresso-shop-reviews-v2
        app.kubernetes.io/instance: espresso-shop-reviews-v2
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: espresso-shop-reviews-v2
      securityContext:
        {}
      containers:
        - name: espresso-shop-reviews-v2
          securityContext:
            {}
          image: "chrisdylan/expresso:reviews"
          imagePullPolicy: Always
          env:
          - name: SERVICE_VERSION
            value: v2
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi

NOTES:
1. Get the application URL by running these commands:
  export NODE_PORT=$(kubectl get --namespace chris2 -o jsonpath="{.spec.ports[0].nodePort}" services espresso-shop-reviews-v2)
  export NODE_IP=$(kubectl get nodes --namespace chris2 -o jsonpath="{.items[0].status.addresses[0].address}")
  echo http://$NODE_IP:$NODE_PORT
